### ISSUE TITLE
Install failure on Ubuntu 23.10 

### ISSUE THREAD

**Issue by unixmiddleware** [bartfeenstra/betty#1044]
Installing on a newly created VM has the same issue as trying to install on a standalone system.

# Ubuntu details

```
(website) mark@aorus:~/workspace/website$ cat /etc/os-release
PRETTY_NAME="Ubuntu 23.10"
NAME="Ubuntu"
VERSION_ID="23.10"
VERSION="23.10 (Mantic Minotaur)"
VERSION_CODENAME=mantic
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=mantic
LOGO=ubuntu-logo
```

# Install command
```
mark@aorus:~/workspace$ python3 -m venv $(pwd)/website
mark@aorus:~/workspace$ cd website/
mark@aorus:~/workspace/website$ source bin/activate
(website) mark@aorus:~/workspace/website$ pip install betty
```

# Install Output

```
Collecting betty
  Using cached betty-0.2.7-py2.py3-none-any.whl (177 kB)
Collecting aiohttp~=3.7 (from betty)
  Obtaining dependency information for aiohttp~=3.7 from https://files.pythonhosted.org/packages/69/8d/769a1e9cdce1c9774dd2edc8f4e94c759256246066e5263de917e5b22a0a/aiohttp-3.9.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata
  Using cached aiohttp-3.9.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (7.4 kB)
Collecting babel~=2.9 (from betty)
  Obtaining dependency information for babel~=2.9 from https://files.pythonhosted.org/packages/86/14/5dc2eb02b7cc87b2f95930310a2cc5229198414919a116b564832c747bc1/Babel-2.13.1-py3-none-any.whl.metadata
  Using cached Babel-2.13.1-py3-none-any.whl.metadata (1.6 kB)
Collecting click~=7.1 (from betty)
  Using cached click-7.1.2-py2.py3-none-any.whl (82 kB)
Collecting docker~=4.4 (from betty)
  Using cached docker-4.4.4-py2.py3-none-any.whl (147 kB)
Collecting urllib3<2 (from betty)
  Obtaining dependency information for urllib3<2 from https://files.pythonhosted.org/packages/b0/53/aa91e163dcfd1e5b82d8a890ecf13314e3e149c05270cc644581f77f17fd/urllib3-1.26.18-py2.py3-none-any.whl.metadata
  Using cached urllib3-1.26.18-py2.py3-none-any.whl.metadata (48 kB)
Collecting geopy~=2.0 (from betty)
  Obtaining dependency information for geopy~=2.0 from https://files.pythonhosted.org/packages/e5/15/cf2a69ade4b194aa524ac75112d5caac37414b20a3a03e6865dfe0bd1539/geopy-2.4.1-py3-none-any.whl.metadata
  Using cached geopy-2.4.1-py3-none-any.whl.metadata (6.8 kB)
Collecting jinja2~=2.11 (from betty)
  Using cached Jinja2-2.11.3-py2.py3-none-any.whl (125 kB)
Collecting jsonschema~=3.2 (from betty)
  Using cached jsonschema-3.2.0-py2.py3-none-any.whl (56 kB)
Collecting libsass~=0.20 (from betty)
  Using cached libsass-0.22.0-cp36-abi3-manylinux_2_5_x86_64.manylinux1_x86_64.whl (9.4 MB)
Collecting markupsafe~=1.1 (from betty)
  Using cached MarkupSafe-1.1.1.tar.gz (19 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting pdf2image~=1.14 (from betty)
  Using cached pdf2image-1.16.3-py3-none-any.whl (11 kB)
Collecting python-resize-image~=1.1 (from betty)
  Using cached python_resize_image-1.1.20-py2.py3-none-any.whl (8.4 kB)
Collecting pyyaml~=5.3 (from betty)
  Using cached PyYAML-5.4.1.tar.gz (175 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [54 lines of output]
      running egg_info
      writing lib3/PyYAML.egg-info/PKG-INFO
      writing dependency_links to lib3/PyYAML.egg-info/dependency_links.txt
      writing top-level names to lib3/PyYAML.egg-info/top_level.txt
      Traceback (most recent call last):
        File "/home/mark/workspace/website/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/home/mark/workspace/website/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/mark/workspace/website/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-w58dccf9/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-w58dccf9/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-w58dccf9/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 271, in <module>
        File "/tmp/pip-build-env-w58dccf9/overlay/lib/python3.11/site-packages/setuptools/__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-w58dccf9/overlay/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-w58dccf9/overlay/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/tmp/pip-build-env-w58dccf9/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/tmp/pip-build-env-w58dccf9/overlay/lib/python3.11/site-packages/setuptools/dist.py", line 963, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-w58dccf9/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-w58dccf9/overlay/lib/python3.11/site-packages/setuptools/command/egg_info.py", line 321, in run
          self.find_sources()
        File "/tmp/pip-build-env-w58dccf9/overlay/lib/python3.11/site-packages/setuptools/command/egg_info.py", line 329, in find_sources
          mm.run()
        File "/tmp/pip-build-env-w58dccf9/overlay/lib/python3.11/site-packages/setuptools/command/egg_info.py", line 551, in run
          self.add_defaults()
        File "/tmp/pip-build-env-w58dccf9/overlay/lib/python3.11/site-packages/setuptools/command/egg_info.py", line 589, in add_defaults
          sdist.add_defaults(self)
        File "/tmp/pip-build-env-w58dccf9/overlay/lib/python3.11/site-packages/setuptools/command/sdist.py", line 112, in add_defaults
          super().add_defaults()
        File "/tmp/pip-build-env-w58dccf9/overlay/lib/python3.11/site-packages/setuptools/_distutils/command/sdist.py", line 251, in add_defaults
          self._add_defaults_ext()
        File "/tmp/pip-build-env-w58dccf9/overlay/lib/python3.11/site-packages/setuptools/_distutils/command/sdist.py", line 336, in _add_defaults_ext
          self.filelist.extend(build_ext.get_source_files())
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "<string>", line 201, in get_source_files
        File "/tmp/pip-build-env-w58dccf9/overlay/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 107, in __getattr__
          raise AttributeError(attr)
      AttributeError: cython_sources
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

```

**Comment by bartfeenstra** [comment]
Hi Mark! Based on your Ubuntu version I suppose you're running Python 3.10 or higher. Unfortunately, Betty 0.2 (the default stable version at the moment) only supports up to Python 3.9. Pip unfortunately does not check this, so that's what gets you that slightly less helpful error.

Betty 0.3 supports Python 3.11 and up. It's functionally feature-complete, but there are some race conditions and performance issues I have been trying to solve before I can publish 0.3.0.

I did just release https://pypi.org/project/betty/0.3.0a1/ so it should be a bit easier for you to install than through the Git source.

**Comment by unixmiddleware** [comment]
Hi Bart

Thanks for the reply, explaining  the issue and possible solutions.
I'll try both options later today.

Best wishes
Mark

**Comment by bartfeenstra** [comment]
Hiya Mark! Any luck on your end? I'm looking to release alpha 2 this week which will include some of the performance and stability improvements I mentioned earlier.

UPDATE: I just released 0.3.0 alpha 2

**Comment by bartfeenstra** [comment]
With https://github.com/bartfeenstra/betty/releases/tag/0.3.0b2 just out I'm fairly confident this issue is resolved. Please reopen it if it persists.

**Comment by unixmiddleware** [comment]
Sorry for the tardy response, there were issues with 0.3.0 alpha2 related to yaml versions, which I meant to tackle but I didn't find the time.
The 0.3.0b2 version has an wayland issue 
`./betty: symbol lookup error: /home/mark/workspace/Betty-0.3.0b2/dist/betty/_internal/libQt6WaylandClient.so.6: undefined symbol: wl_proxy_marshal_flags
`
This seems to be well known and is an [ubuntu packaging error](https://bugreports.qt.io/browse/QTBUG-114635).

**Comment by bartfeenstra** [comment]
@unixmiddleware Can you try https://github.com/bartfeenstra/betty/pull/1129? The Betty Desktop Linux build should be posted in a comment there within a few minutes.

**Comment by bartfeenstra** [comment]
I'm temporarily removing the PyInstaller/desktop application builds for Linux in https://github.com/bartfeenstra/betty/pull/1157 until we can figure out how to make them work.

**Comment by unixmiddleware** [comment]
Just try again, after a software update,  and the qt issues are resolved
and Betty installs nicely in a python virtual environment.

**Comment by bartfeenstra** [comment]
That's good to hear! :)
