### ISSUE TITLE
Locale-handling code cannot cope with missing locales or generic ISO-639 codes

### ISSUE THREAD

**Issue by unixmiddleware** [bartfeenstra/betty#626]
With config
locales:
   - locale: en-US
     alias: en

on Debian 10, generate fails with: 
    AttributeError: 'NoneType' object has no attribute 'split'
    Checking that the available_locale is not None resolves this issue
        ...
        if not available_locale is None:
            negotiated_locale = babel.negotiate_locale(
                [preferred_locale], [available_locale.split('-', 1)[0]])

**Comment by bartfeenstra** [comment]
Thanks for reporting this. `available_locales` must only contains string, so the fact it contains `None` indicates a problem elswhere. Let me see what I can find.

**Comment by bartfeenstra** [comment]
@unixmiddleware Can you post a full stack trace?

**Comment by unixmiddleware** [comment]
NoneType' object has no attribute 'split'
Traceback (most recent call last):
  File "/home/mark/workspace/betty-pr/betty/betty/cli.py", line 35, in catch_exceptions
    yield
  File "/home/mark/.conda/envs/gramps/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/home/mark/workspace/betty-pr/betty/betty/asyncio.py", line 10, in _synced
    return sync(f(*args, **kwargs))
  File "/home/mark/workspace/betty-pr/betty/betty/asyncio.py", line 16, in sync
    return asyncio.get_event_loop().run_until_complete(f)
  File "/home/mark/.conda/envs/gramps/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/mark/workspace/betty-pr/betty/betty/cli.py", line 54, in _command
    await f(*args, **kwargs)
  File "/home/mark/workspace/betty-pr/betty/betty/cli.py", line 144, in _generate
    await generate.generate(site)
  File "/home/mark/workspace/betty-pr/betty/betty/generate.py", line 54, in generate
    await _generate_entity_type(www_directory_path, site.ancestry.places.values(
  File "/home/mark/workspace/betty-pr/betty/betty/generate.py", line 101, in _generate_entity_type
    await _generate_entity(www_directory_path, entity,
  File "/home/mark/workspace/betty-pr/betty/betty/generate.py", line 133, in _generate_entity
    await _generate_entity_html(www_directory_path, entity,
  File "/home/mark/workspace/betty-pr/betty/betty/generate.py", line 142, in _generate_entity_html
    f.write(await environment.get_template('page/%s.html.j2' % entity_type_name).render_async({
  File "/home/mark/.conda/envs/gramps/lib/python3.8/site-packages/jinja2/asyncsupport.py", line 65, in render_async
    return self.environment.handle_exception()
  File "/home/mark/.conda/envs/gramps/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/mark/.conda/envs/gramps/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/mark/.conda/envs/gramps/lib/python3.8/site-packages/jinja2/asyncsupport.py", line 25, in concat_async
    await collect()
  File "/home/mark/.conda/envs/gramps/lib/python3.8/site-packages/jinja2/asyncsupport.py", line 22, in collect
    async for event in async_gen:
  File "/home/mark/workspace/betty-pr/betty/betty/assets/templates/page/place.html.j2", line 2, in top-level template code
    {% set page_title = place.names | negotiate_localizeds %}
  File "/home/mark/workspace/betty-pr/betty/betty/assets/templates/base.html.j2", line 128, in top-level template code
    {% set links = links | select_localizeds | list + links | selectattr('locale', 'none') | list %}
  File "/home/mark/.conda/envs/gramps/lib/python3.8/site-packages/jinja2/asyncsupport.py", line 174, in auto_await
    return await value
  File "/home/mark/.conda/envs/gramps/lib/python3.8/site-packages/jinja2/asyncfilters.py", line 93, in do_list
    return await auto_to_seq(value)
  File "/home/mark/.conda/envs/gramps/lib/python3.8/site-packages/jinja2/asyncfilters.py", line 14, in auto_to_seq
    for item in value:
  File "/home/mark/workspace/betty-pr/betty/betty/jinja2.py", line 441, in _filter_select_localizeds
    if negotiate_locale(locale, [localized.locale]) is not None:
  File "/home/mark/workspace/betty-pr/betty/betty/locale.py", line 269, in negotiate_locale
    [preferred_locale], [available_locale.split('-', 1)[0]])
AttributeError: 'NoneType' object has no attribute 'split'

**Comment by unixmiddleware** [comment]
In case it helps, negotiate_locale is called 3 times before the error arises:

Privatized 67 people because they are likely still alive.
available_locale[0] = en-US
available_locale[0] = arz
Generated pages for 36 files in English (United States).
Generated pages for 26 people in English (United States).
available_locale[0] = None
Built the interactive family trees.

**Comment by unixmiddleware** [comment]
With a check that the available_locale is not None, the negotiate_locale is called 4 times before the Person unhashable error occurs

Privatized 67 people because they are likely still alive.
available_locale[0] = en-US
available_locale[0] = arz
Generated pages for 36 files in English (United States).
Generated pages for 26 people in English (United States).
available_locale[0] = None
available_locale[0] = en
Generated pages for 13 places in English (United States).

**Comment by bartfeenstra** [comment]
Thanks. I dug through this and it's because we don't yet accommodate for missing locale information when taking a list of localized data. In this case some of the (external) links associated with resources in your family do not specify a locale and the current code does not know how to handle that. Similarly if localized data *does* specify a locale, but it's `mis`, `mul`, `und`, or `zxx`, our code can't handle that either. It won't error on those cases, but it'll needlessly filter out the localized data. We'll need to add support for all five cases.

**Comment by bartfeenstra** [comment]
@unixmiddleware Does https://github.com/bartfeenstra/betty/pull/634 solve the problems you are experiencing?

**Comment by unixmiddleware** [comment]
The problems have been resolved, no issues at all now

**Comment by bartfeenstra** [comment]
Thanks for the review. Fixed on `0.2.x` and `master`!
